### ISSUE TITLE
Audio playback speed below 1x results in echo

### ISSUE THREAD

**Issue by Sidelobe** [republik/app#280] opened 2023-08-23 11:52 UTC
### Bug Description

When I set playback speed (vorgelesene Artikel) below 1x, the audio is disturbed by an echo.

### Expected Behaviour

The audio should be slowed down without echo

### Steps to reproduce

Set playback to 0.75 while playing an article

### Environment

App (iOS/iPadOS)

### Version

2.2.3

**Comment by trm217** [comment] 2023-09-06 09:31
@Sidelobe thanks for reporting the issue, it appears that it might be an issue caused by the audio-library that we use for the playback. We'll look into it.

**Comment by trm217** [comment] 2023-09-06 09:31
Reference to the above mentioned issue in react-native-trackplayer: https://github.com/doublesymmetry/react-native-track-player/issues/682

**Comment by ovbm** [comment] 2023-09-07 20:08
fixed via https://github.com/republik/app/commit/c5d7223546ec279a170551f74ecd673fc9f3aab0

**Closed by ovbm** 2023-09-07 20:08 UTC
Labels: bug, iOS
